apiVersion: v1
kind: Service
metadata:
  name: kube-echo-svc
  labels:
    svc: kube-echo-svc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30050
  selector:
    run: kube-echo
